create table users (
    id bigint generated by default as identity primary key,
    created_at timestamp not null,
    updated_at timestamp not null,
    username varchar(50) not null,
    email varchar(120) not null,
    password varchar(255) not null,
    first_name varchar(80) not null,
    last_name varchar(80) not null,
    active boolean not null,
    roles varchar(100) not null,
    constraint uk_users_username unique (username),
    constraint uk_users_email unique (email)
);

create table user_preferences (
    id bigint generated by default as identity primary key,
    created_at timestamp not null,
    updated_at timestamp not null,
    user_id bigint not null,
    default_locale varchar(10) not null,
    default_timezone varchar(80) not null,
    default_currency varchar(3) not null,
    date_format varchar(20) not null,
    number_format_locale varchar(10) not null,
    constraint uk_user_preferences_user unique (user_id),
    constraint fk_user_preferences_user foreign key (user_id) references users (id)
);

create table accounts (
    id bigint generated by default as identity primary key,
    created_at timestamp not null,
    updated_at timestamp not null,
    user_id bigint not null,
    name varchar(100) not null,
    type varchar(30) not null,
    currency varchar(3) not null,
    initial_balance numeric(14, 2) not null,
    current_balance numeric(14, 2) not null,
    active boolean not null,
    institution_name varchar(120),
    color varchar(7),
    notes text,
    constraint fk_accounts_user foreign key (user_id) references users (id)
);

create table categories (
    id bigint generated by default as identity primary key,
    created_at timestamp not null,
    updated_at timestamp not null,
    user_id bigint not null,
    name varchar(100) not null,
    type varchar(30) not null,
    parent_category_id bigint,
    color varchar(7),
    active boolean not null,
    constraint fk_categories_user foreign key (user_id) references users (id),
    constraint fk_categories_parent foreign key (parent_category_id) references categories (id),
    constraint uk_categories_user_name_type unique (user_id, name, type)
);

create table transactions (
    id bigint generated by default as identity primary key,
    created_at timestamp not null,
    updated_at timestamp not null,
    user_id bigint not null,
    account_id bigint not null,
    destination_account_id bigint,
    category_id bigint,
    type varchar(30) not null,
    status varchar(30) not null,
    source varchar(30) not null,
    amount numeric(14, 2) not null,
    transaction_date date not null,
    description varchar(255) not null,
    notes text,
    import_batch_id bigint,
    constraint fk_transactions_user foreign key (user_id) references users (id),
    constraint fk_transactions_account foreign key (account_id) references accounts (id),
    constraint fk_transactions_destination_account foreign key (destination_account_id) references accounts (id),
    constraint fk_transactions_category foreign key (category_id) references categories (id)
);

create index idx_accounts_user on accounts (user_id);
create index idx_categories_user_type on categories (user_id, type);
create index idx_transactions_user_date on transactions (user_id, transaction_date);
create index idx_transactions_account_date on transactions (account_id, transaction_date);
create index idx_transactions_type on transactions (type);
