create table counterparties (
    id bigint generated by default as identity primary key,
    created_at timestamp not null,
    updated_at timestamp not null,
    user_id bigint not null,
    name varchar(140) not null,
    document varchar(30),
    type varchar(30) not null,
    notes text,
    constraint fk_counterparties_user foreign key (user_id) references users (id)
);

create table tags (
    id bigint generated by default as identity primary key,
    created_at timestamp not null,
    updated_at timestamp not null,
    user_id bigint not null,
    name varchar(80) not null,
    color varchar(7),
    constraint fk_tags_user foreign key (user_id) references users (id),
    constraint uk_tags_user_name unique (user_id, name)
);

alter table transactions add column counterparty_id bigint;
alter table transactions add constraint fk_transactions_counterparty foreign key (counterparty_id) references counterparties (id);

create table transaction_tags (
    transaction_id bigint not null,
    tag_id bigint not null,
    primary key (transaction_id, tag_id),
    constraint fk_transaction_tags_transaction foreign key (transaction_id) references transactions (id),
    constraint fk_transaction_tags_tag foreign key (tag_id) references tags (id)
);

create table transaction_splits (
    id bigint generated by default as identity primary key,
    created_at timestamp not null,
    updated_at timestamp not null,
    transaction_id bigint not null,
    category_id bigint,
    amount numeric(14, 2) not null,
    description varchar(255),
    constraint fk_transaction_splits_transaction foreign key (transaction_id) references transactions (id),
    constraint fk_transaction_splits_category foreign key (category_id) references categories (id)
);

create table import_batches (
    id bigint generated by default as identity primary key,
    created_at timestamp not null,
    updated_at timestamp not null,
    user_id bigint not null,
    account_id bigint not null,
    filename varchar(255) not null,
    file_size bigint,
    status varchar(30) not null,
    total_records integer not null,
    valid_records integer not null,
    invalid_records integer not null,
    duplicate_records integer not null,
    error_message text,
    processed_at timestamp,
    constraint fk_import_batches_user foreign key (user_id) references users (id),
    constraint fk_import_batches_account foreign key (account_id) references accounts (id)
);

create table imported_records (
    id bigint generated by default as identity primary key,
    created_at timestamp not null,
    updated_at timestamp not null,
    batch_id bigint not null,
    line_number integer not null,
    raw_payload text not null,
    parsed_date date,
    parsed_amount numeric(14, 2),
    parsed_description varchar(255),
    parsed_type varchar(30),
    deduplication_hash varchar(64) not null,
    status varchar(30) not null,
    error_message text,
    transaction_id bigint,
    constraint fk_imported_records_batch foreign key (batch_id) references import_batches (id),
    constraint fk_imported_records_transaction foreign key (transaction_id) references transactions (id)
);

create index idx_counterparties_user on counterparties (user_id);
create index idx_tags_user on tags (user_id);
create index idx_transactions_counterparty on transactions (counterparty_id);
create index idx_transaction_splits_transaction on transaction_splits (transaction_id);
create index idx_import_batches_user_status on import_batches (user_id, status);
create index idx_imported_records_batch_status on imported_records (batch_id, status);
create index idx_imported_records_hash_status on imported_records (deduplication_hash, status);
