-- V4__loans_and_ml_views.sql
-- Migration for Loans Module and ML View

-- 1. Loans Table
CREATE TABLE loans (
    id bigint generated by default as identity primary key,
    created_at timestamp not null,
    updated_at timestamp not null,
    user_id bigint not null,
    name varchar(150) not null,
    principal_amount numeric(14, 2) not null,
    current_balance numeric(14, 2) not null,
    loan_type varchar(30) not null,
    counterparty_id bigint,
    start_date date not null,
    end_date date,
    interest_rate numeric(10, 4),
    status varchar(30) not null,
    notes text,
    deleted_at timestamp,
    constraint fk_loans_user foreign key (user_id) references users (id),
    constraint fk_loans_counterparty foreign key (counterparty_id) references counterparties (id)
);

CREATE INDEX idx_loans_user ON loans (user_id);
CREATE INDEX idx_loans_status ON loans (status);

-- 2. Loan Movements Table
CREATE TABLE loan_movements (
    id bigint generated by default as identity primary key,
    created_at timestamp not null,
    updated_at timestamp not null,
    loan_id bigint not null,
    transaction_id bigint,
    type varchar(30) not null,
    amount numeric(14, 2) not null,
    movement_date date not null,
    description varchar(255) not null,
    constraint fk_loan_movements_loan foreign key (loan_id) references loans (id),
    constraint fk_loan_movements_tx foreign key (transaction_id) references transactions (id)
);

CREATE INDEX idx_loan_movements_loan ON loan_movements (loan_id);

-- 3. Data Science ML View
CREATE VIEW v_fact_transactions_ml AS
SELECT 
    v.*,
    
    -- Derived Feature: signed_amount
    -- Positive for INCOME, Negative for EXPENSE and others
    CASE 
        WHEN v.transaction_type = 'INCOME' THEN v.amount
        WHEN v.transaction_type = 'EXPENSE' THEN -v.amount
        ELSE 0 
    END AS signed_amount,
    
    -- Derived Feature: is_weekend (0=Sunday, 6=Saturday in PostgreSQL EXTRACT DOW)
    -- Using compatible logic for H2/Postgres if possible. 
    -- In H2/PG, DOW returns 0-6 (Sun-Sat) or 1-7 (Mon-Sun) depending on mode.
    -- PostgreSQL: EXTRACT(ISODOW from date) returns 1 (Mon) to 7 (Sun)
    CASE 
        WHEN EXTRACT(ISODOW FROM v.transaction_date) IN (6, 7) THEN TRUE
        ELSE FALSE 
    END AS is_weekend,
    
    -- Derived Feature: is_month_start (days 1 to 5)
    CASE 
        WHEN EXTRACT(DAY FROM v.transaction_date) <= 5 THEN TRUE
        ELSE FALSE 
    END AS is_month_start,
    
    -- Derived Feature: is_month_end (days 25 to 31)
    CASE 
        WHEN EXTRACT(DAY FROM v.transaction_date) >= 25 THEN TRUE
        ELSE FALSE 
    END AS is_month_end

FROM v_fact_transactions v;
