-- V5__planning_and_projection.sql

-- 1. Budgets Table
CREATE TABLE category_budgets (
    id bigint generated by default as identity primary key,
    created_at timestamp not null,
    updated_at timestamp not null,
    user_id bigint not null,
    category_id bigint not null,
    amount_limit numeric(14, 2) not null,
    active boolean not null default true,
    constraint fk_category_budgets_user foreign key (user_id) references users (id),
    constraint fk_category_budgets_cat foreign key (category_id) references categories (id),
    constraint uq_user_category_budget unique (user_id, category_id)
);

-- 2. Goals Table
CREATE TABLE goals (
    id bigint generated by default as identity primary key,
    created_at timestamp not null,
    updated_at timestamp not null,
    user_id bigint not null,
    name varchar(150) not null,
    target_amount numeric(14, 2) not null,
    current_amount numeric(14, 2) not null default 0,
    target_date date,
    status varchar(30) not null,
    color varchar(10),
    constraint fk_goals_user foreign key (user_id) references users (id)
);

-- 3. Update Transactions for Recurrence
ALTER TABLE transactions ADD COLUMN recurrence_frequency varchar(30);
ALTER TABLE transactions ADD COLUMN recurrence_end_date date;
ALTER TABLE transactions ADD COLUMN original_transaction_id bigint;

-- 4. Recreate v_monthly_cashflow to include status
DROP VIEW IF EXISTS v_monthly_cashflow;

CREATE VIEW v_monthly_cashflow AS
SELECT
    user_id,
    TO_CHAR(transaction_date, 'YYYY-MM') AS year_month,
    status AS transaction_status,
    COALESCE(SUM(CASE WHEN type = 'INCOME' THEN amount ELSE 0 END), 0) AS total_income,
    COALESCE(SUM(CASE WHEN type = 'EXPENSE' THEN amount ELSE 0 END), 0) AS total_expense,
    COALESCE(SUM(CASE WHEN type = 'INCOME' THEN amount ELSE 0 END), 0) - COALESCE(SUM(CASE WHEN type = 'EXPENSE' THEN amount ELSE 0 END), 0) AS net_cashflow
FROM transactions
WHERE type IN ('INCOME', 'EXPENSE') 
  AND status IN ('POSTED', 'PENDING')
GROUP BY user_id, EXTRACT(YEAR FROM transaction_date), EXTRACT(MONTH FROM transaction_date), TO_CHAR(transaction_date, 'YYYY-MM'), status;
